### ISSUE TITLE
Android Bug No implementation found for int com.jamol.kuma.WebSocket.connect

### ISSUE THREAD

**Issue by BadDeveloper2022** [Jamol/kuma#43]
No implementation found for int com.jamol.kuma.WebSocket.connect(java.lang.String) (tried Java_com_jamol_kuma_WebSocket_connect and Java_com_jamol_kuma_WebSocket_connect__Ljava_lang_String_2)
2023-11-07 15:00:43.644  8361-8580  AndroidRuntime          com.feihong.tx100test                E  FATAL EXCEPTION: Thread-5
                                                                                                    Process: com.feihong.tx100test, PID: 8361
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for int com.jamol.kuma.WebSocket.connect(java.lang.String) (tried Java_com_jamol_kuma_WebSocket_connect and Java_com_jamol_kuma_WebSocket_connect__Ljava_lang_String_2)
                                                                                                    	at com.jamol.kuma.WebSocket.connect(Native Method)
                                                                                                    	at com.jamol.kuma.WebSocket.open(WebSocket.java:11)

**Comment by Jamol** [comment]
I'll reimplement android API with kotlin, corrently the WebSocket API is completed, please try it.

**Comment by Jamol** [comment]
android API folder: android/kuma
android demo folder: test/android/kmtest
